import { Inter, Poppins } from "next/font/google";
import "./globals.css";

const inter = Poppins({ weight: "200", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}  body`}>{children}</body>
    </html>
  );
}
